on: [push, pull_request]

name: CI

env:
  DESTDIR: "${{ github.workspace }}/dist"
  MESON: "${{ github.workspace }}/repo/meson.sh"

jobs:
  "Meson_Compile_Naev":

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            shell: bash
            config: linux.ini

          - os: windows-latest
            shell: msys2 {0}
            config: windows.ini
            
    defaults:
      run:
        shell: ${{ matrix.shell }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Update APT Cache
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          build-essential \
          binutils-dev \
          gettext \
          intltool \
          libsdl2-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libgl1-mesa-dri \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev \
          llvm \
          ninja-build \
          xvfb

    - name: Install MinGW Packages
      if: ${{ runner.os == 'Windows'}}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        path-type: strict
        install: git tar mingw-w64-x86_64-clang mingw-w64-x86_64-freetype mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libxml2 mingw-w64-x86_64-make mingw-w64-x86_64-mesa mingw-w64-x86_64-meson mingw-w64-x86_64-ninja mingw-w64-x86_64-openal mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2

    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: repo
        fetch-depth: 0

    - name:  Package Meson Dist
      run: |
        sh $MESON setup dist repo -Dexecutable=disabled -Ddocs_c=disabled -Ddocs_lua=disabled
        sh $MESON dist -C dist --no-tests --include-subprojects
        
    - name: Upload Meson Dist Artifact
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: naikari-meson-dist-${{ github.sha }}
        path: ${{ github.workspace }}/dist/meson-dist/*
        if-no-files-found: error
        
    - name: Extract Source
      run: |
        mkdir source
        tar -xf dist/meson-dist/naikari-*.tar.xz -C source --strip 1
      working-directory: "${{ github.workspace }}"

    - name: Meson Setup
      id: setup
      run: |
        sh $MESON setup build source \
            --native-file='source/utils/build/${{ matrix.config }}' \
            --buildtype=debug \
            -Db_lto=true \
            -Dauto_features=enabled \
            -Ddocs_c=disabled \
            -Ddocs_lua=disabled

    - name: Upload Setup Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.setup.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-setup-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

    - name: Meson Compile
      id: compile
      run: |
        sh $MESON compile -C build

    - name: Upload Compile Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.compile.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-compile-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

    - name: Meson Test
      id: tests
      run: |
        sh $MESON test -C build --print-errorlogs

    - name: Upload Test Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.tests.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-test-log
        path: ${{ github.workspace }}/build/meson-logs/testlog.txt
        if-no-files-found: ignore

    - name: Test Meson Install
      run: |
        sh $MESON install -C build

    - name: Upload Install Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.compile.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-install-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

  "AppImage_Compile_Naev":
    needs: Meson_Compile_Naev
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildtype: meson

    runs-on: ubuntu-16.04

    steps:
    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          binutils-dev \
          build-essential \
          gettext \
          intltool \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libiberty-dev \
          libopenal-dev \
          libpng-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libvorbis-dev \
          libxml2-dev \
          ninja-build=1.7.1-1~ubuntu16.04.1
        sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-9 90

    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: repo
        fetch-depth: 0

    - name: Compile AppImage Meson
      id: mesonCompile
      run: |
        ./repo/utils/buildAppImage.sh -c -m -s "repo" -b "build" -o "${{ env.DESTDIR }}" |& tee -a appImageBuildLog.txt

    - name: Upload Compile Log
      uses: actions/upload-artifact@v2
      if: ${{ (success() || steps.mesonCompile.outcome == 'failure') }}
      with:
        name: naikari-${{ github.sha }}-${{ matrix.buildtype }}AppImageBuild-log
        path: ${{ github.workspace }}/appImageBuildLog.txt
        if-no-files-found: ignore

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naikari-${{ matrix.buildtype }}AppImage-${{ github.sha }}
        path: "${{ env.DESTDIR }}/out/*.AppImage"
        if-no-files-found: error

  "Documentation":
    needs: [AppImage_Compile_Naev, Meson_Compile_Naev]
    runs-on: ubuntu-20.04

    steps:
    - name: Update APT Cache
      run: |
        sudo apt-get update
        
    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          lua-ldoc \
          graphviz \
          doxygen \
          ninja-build
          
    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: repo
        fetch-depth: 0
        
    - name: Meson Build
      run: |
        sh $MESON setup build repo \
            -Dexecutable=disabled
