on: [push, pull_request]

name: CI

env:
  DESTDIR: "${{ github.workspace }}/dist"
  MESON: "${{ github.workspace }}/source/meson.sh"

jobs:
  "Test_Dist":
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - buildtype: meson
          - buildtype: autotools

    steps:
    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          automake \
          autopoint \
          autoconf-archive \
          build-essential \
          binutils-dev \
          gettext \
          intltool \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev \
          ninja-build

    - name:  Package Meson Dist
      if: ${{ matrix.buildtype == 'meson' }}
      run: |
        sh $MESON setup build source -Dexecutable=disabled -Ddocs_c=disabled -Ddocs_lua=disabled
        sh $MESON dist -C build --no-tests --include-subprojects

    - name: Package Autotools Dist
      if: ${{ matrix.buildtype == 'autotools' }}
      run: |
          ./autogen.sh
          ./configure
          make dist-gzip
          #make distcheck (broken)
      working-directory: "source"

    - name: Upload Meson Dist Artifact
      if: ${{ matrix.buildtype == 'meson' }}
      uses: actions/upload-artifact@v2
      with:
        name: naikari-meson-dist-${{ github.sha }}
        path: ${{ github.workspace }}/build/meson-dist/*
        if-no-files-found: error

    - name: Upload Autotools Dist Artifact
      if: ${{ matrix.buildtype == 'autotools' }}
      uses: actions/upload-artifact@v2
      with:
        name: naikari-autotools-dist-${{ github.sha }}
        path: ${{ github.workspace }}/source/naikari-*.tar.gz
        if-no-files-found: error

  "Meson_Compile_Naev":

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            shell: bash
            config: linux.ini

          - os: windows-latest
            shell: msys2 {0}
            config: windows.ini
            
    defaults:
      run:
        shell: ${{ matrix.shell }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Update APT Cache
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          automake \
          autopoint \
          autoconf-archive \
          build-essential \
          binutils-dev \
          gettext \
          intltool \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libgl1-mesa-dri \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev \
          ninja-build \
          xvfb

    - name: Install MinGW Packages
      if: ${{ runner.os == 'Windows'}}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        path-type: strict
        install: git tar mingw-w64-x86_64-clang mingw-w64-x86_64-freetype mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libxml2 mingw-w64-x86_64-luajit mingw-w64-x86_64-mesa mingw-w64-x86_64-meson mingw-w64-x86_64-ninja mingw-w64-x86_64-openal mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-suitesparse

    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Meson Setup
      id: setup
      run: |
        sh $MESON setup build source \
            --native-file='source/utils/build/${{ matrix.config }}' \
            --buildtype=release \
            -Db_lto=true \
            -Dauto_features=enabled \
            -Ddocs_c=disabled \
            -Ddocs_lua=disabled

    - name: Upload Setup Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.setup.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-setup-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

    - name: Meson Compile
      id: compile
      run: |
        sh $MESON compile -C build

    - name: Upload Compile Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.compile.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-compile-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

    - name: Meson Test
      id: tests
      run: |
        sh $MESON test -C build --print-errorlogs

    - name: Upload Test Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.tests.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-install-log
        path: ${{ github.workspace }}/build/meson-logs/testlog.txt
        if-no-files-found: ignore

    - name: Test Meson Install
      run: |
        sh $MESON install -C build

    - name: Upload Install Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.compile.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-meson-${{ github.sha }}-install-log
        path: ${{ github.workspace }}/build/meson-logs/meson-log.txt
        if-no-files-found: ignore

  "Autotools_Compile_Naev":

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            shell: bash

          - os: windows-latest
            shell: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Update APT Cache
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          build-essential \
          automake \
          autopoint \
          autoconf-archive \
          binutils-dev \
          gettext \
          intltool \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev 

    - name: Install MinGW Packages
      if: ${{ runner.os == 'Windows'}}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        path-type: strict
        install: mingw-w64-x86_64-libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libpng mingw-w64-x86_64-openal mingw-w64-x86_64-libvorbis mingw-w64-x86_64-binutils mingw-w64-x86_64-freetype mingw-w64-x86_64-gettext mingw-w64-x86_64-luajit mingw-w64-x86_64-pkg-config libtool autoconf autoconf-archive automake automake-wrapper git gettext pkg-config make intltool itstool

    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Autotools Setup
      run: |
        ./autogen.sh
        ./configure
      working-directory: source

    - name: Autotools Compile
      run: |
        make -j"$(nproc)"
      working-directory: source

    - name: Test Autotools Install
      run: |
        make install
      working-directory: source

  "AppImage_Compile_Naev":
    needs: [Meson_Compile_Naev, Autotools_Compile_Naev]
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildtype: meson
          - buildtype: autotools

    runs-on: ubuntu-16.04

    steps:
    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          autopoint \
          automake \
          autoconf-archive \
          binutils-dev \
          build-essential \
          gettext \
          intltool \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libiberty-dev \
          libluajit-5.1-dev \
          libopenal-dev \
          libpng-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsuitesparse-dev \
          libvorbis-dev \
          libxml2-dev \
          ninja-build=1.7.1-1~ubuntu16.04.1

    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Compile AppImage Autotools
      if: ${{ matrix.buildtype == 'autotools' }}
      id: autotoolsCompile
      run: |
        ./source/utils/buildAppImage.sh -c -s "source" -b "source" -o "${{ env.DESTDIR }}" |& tee -a appImageBuildLog.txt

    - name: Compile AppImage Meson
      if: ${{ matrix.buildtype == 'meson' }}
      id: mesonCompile
      run: |
        ./source/utils/buildAppImage.sh -m -s "source" -b "build" -o "${{ env.DESTDIR }}" |& tee -a appImageBuildLog.txt

    - name: Upload Compile Log
      uses: actions/upload-artifact@v2
      if: ${{ (success() || steps.mesonCompile.outcome == 'failure' || steps.autotoolsCompile.outcome == 'failure') }}
      with:
        name: ${{ matrix.os }}-${{ github.sha }}-${{ matrix.buildtype }}AppImageBuild-log
        path: ${{ github.workspace }}/appImageBuildLog.txt
        if-no-files-found: ignore

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naikari-${{ matrix.buildtype }}AppImage-${{ github.sha }}
        path: "${{ env.DESTDIR }}/out/*.AppImage"
        if-no-files-found: error

  "Documentation":
    needs: [AppImage_Compile_Naev, Test_Dist]
    runs-on: ubuntu-20.04

    steps:
    - name: Update APT Cache
      run: |
        sudo apt-get update
        
    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          lua-ldoc \
          graphviz \
          doxygen \
          ninja-build
          
    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0
        
    - name: Meson Build
      run: |
        sh $MESON setup build source \
            -Dexecutable=disabled
